# Generated by Django 4.1.7 on 2023-03-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contract_code', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_type', models.CharField(choices=[('Sales', 'Sales'), ('Acquisition', 'Acquisition')], max_length=255)),
                ('licensor', models.CharField(max_length=255)),
                ('distributor', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Internal', 'Internal'), ('Cancelled', 'Cancelled')], max_length=255)),
                ('deal_status', models.CharField(choices=[('Long Form Executed', 'Long Form Executed'), ('In Negotiation', 'In Negotiation'), ('Deal Memo Executed', 'Deal Memo Executed'), ('Cancelled', 'Cancelled')], max_length=255)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('deal_type', models.CharField(choices=[('Flat Fee', 'Flat Fee'), ('[Royalties/Revenue Share]', '[Royalties/Revenue Share]'), ('Minimum Guarantee', 'Minimum Guarantee'), ('Straight Distribution', 'Straight Distribution'), ('[MG] [++MG]', '[MG] [++MG]'), ('Production / License Agrmnt', 'Production / License Agrmnt'), ('Volume Deal', 'Volume Deal'), ('Co-Production', 'Co-Production'), ('Output Agrmnt', 'Output Agrmnt')], max_length=255)),
                ('fully_executed', models.DateField(blank=True, null=True)),
                ('mg', models.FloatField(blank=True, null=True)),
                ('cur', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_terms', models.CharField(blank=True, max_length=50000, null=True)),
                ('contract', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contracts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('continent', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('right', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('row', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('title', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('aka_1', models.CharField(blank=True, max_length=255, null=True)),
                ('aka_2', models.CharField(blank=True, max_length=255, null=True)),
                ('adj_running_time', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_year', models.CharField(blank=True, max_length=255, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('dialogue_language', models.CharField(blank=True, max_length=255, null=True)),
                ('external_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_code', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('logline', models.CharField(blank=True, max_length=255, null=True)),
                ('motion_picture_association_of_america', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_episodes', models.IntegerField(blank=True, null=True)),
                ('number_of_seasons', models.IntegerField(blank=True, null=True)),
                ('original_format', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(blank=True, max_length=255, null=True)),
                ('production_company', models.CharField(blank=True, max_length=255, null=True)),
                ('project_code', models.CharField(blank=True, max_length=255, null=True)),
                ('project_group', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('running_time', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_agency', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.FloatField(blank=True, null=True)),
                ('short_synopsis', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle_language', models.CharField(blank=True, max_length=255, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=50000, null=True)),
                ('title_code', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('year_completed', models.FloatField(blank=True, null=True)),
                ('web_site', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('us_box_office', models.CharField(blank=True, max_length=255, null=True)),
                ('latam_box_office', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_link', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_usa', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_mexico', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_brazil', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_argentina', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_bolivia', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_chile', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_colombia', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_costa_rica', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_ecuador', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_el_salvador', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_guatemala', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_honduras', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_nicaragua', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_panama', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_paraguay', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_peru', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_dominican_republic', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_uruguay', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_venezuela', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'titles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('license_type', models.CharField(choices=[('License', 'License'), ('Non-Exclusive', 'Non-Exclusive'), ('Holdback', 'Holdback')], max_length=255)),
                ('start_confirmed', models.BooleanField(db_column='Start Confirmed')),
                ('end_confirmed', models.BooleanField(db_column='End Confirmed')),
                ('window', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'windows',
                'managed': False,
            },
        ),
    ]
